// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKrz729FF3UQ1h1ZK63Rlzi-NIegjWkAA',
    appId: '1:781292013877:web:de91d93110b0a20347e47c',
    messagingSenderId: '781292013877',
    projectId: 'hubike-4e954',
    authDomain: 'hubike-4e954.firebaseapp.com',
    storageBucket: 'hubike-4e954.firebasestorage.app',
    measurementId: 'G-HRZVTB923X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL5NsDFwYSpZZ8u7RTij7BsRohRnGkf0k',
    appId: '1:781292013877:android:7972f447b2a52a0247e47c',
    messagingSenderId: '781292013877',
    projectId: 'hubike-4e954',
    storageBucket: 'hubike-4e954.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoGs4lLc2DkuFgPsvqSRYhUvgtxczpt0c',
    appId: '1:781292013877:ios:1638a46d7120f5aa47e47c',
    messagingSenderId: '781292013877',
    projectId: 'hubike-4e954',
    storageBucket: 'hubike-4e954.firebasestorage.app',
    iosBundleId: 'com.example.hubike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoGs4lLc2DkuFgPsvqSRYhUvgtxczpt0c',
    appId: '1:781292013877:ios:1638a46d7120f5aa47e47c',
    messagingSenderId: '781292013877',
    projectId: 'hubike-4e954',
    storageBucket: 'hubike-4e954.firebasestorage.app',
    iosBundleId: 'com.example.hubike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKrz729FF3UQ1h1ZK63Rlzi-NIegjWkAA',
    appId: '1:781292013877:web:a9a338669766ac3b47e47c',
    messagingSenderId: '781292013877',
    projectId: 'hubike-4e954',
    authDomain: 'hubike-4e954.firebaseapp.com',
    storageBucket: 'hubike-4e954.firebasestorage.app',
    measurementId: 'G-0QR0640729',
  );
}
